Update helpers.py
Should Fix errors like 
RuntimeError: Error(s) in loading state_dict for EfficientDet:
    Missing key(s) in state_dict: "backbone.conv_stem.weight", "backbone.bn1.weight", ...
   Unexpected key(s) in state_dict: "model.model.backbone.conv_stem.weight", "model.model.backbone.bn1.weight", "model.model.backbone.bn1.bias", "model.model.backbone.bn1.running_mean", "model.model.backbone.bn1.running_var", "model.model.backbone.bn1.num_batches_tracked", "model.model.backbone.blocks.0.0.conv_dw.weight",